### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [ehmicky/validate-path#1]
hi @ehmicky 

I contribute to open source projects that do not have logo. I have designed a functional logo for validatepath. If you want to use it you can represent your repository better. What do you think? I will wait for feedback. Have a nice day!

![vp](https://user-images.githubusercontent.com/36298335/56582670-73b78f00-65e0-11e9-8fc1-064ba07b43ba.jpg)

**Comment by ehmicky** [comment]
Hi @reallinfo,

Thanks that's very nice!

How did you come to choose this repository? At the moment, this repository is not finished yet. Also it has not been promoted and is not used by anyone (no downloads on npm).

Also what's the logos license?

**Comment by reallinfo** [comment]
I'm reviewing the github repo in the topics menu. I contribute to projects that need logo. I found your repository on the list on topics > node.js.  Also, The logo is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/) 

I sent a pr. I added the license of the logo to the readme file. Please check it. I hope it has been as you wish.

**Comment by ehmicky** [comment]
CC-BY looks good!

There are a few potential tweaks:
  1) What's the font used in the logo?
  2) Would it be possible to add a dash between `validate` and `path`? This is to make sure users don't type `npm install validatepath` instead of `npm install validate-path`.
  3) Would it be possible to make `validate` lowercase? This is to make sure capitalization is consistent.
  4) Do you have it under the following formats as well?
       - SVG
       - Photoshop, Illustrator, Inkscape or Gimp (depending on which tool you used)

Also, I happened to actually usually design my own logos, so I use a different repository for that [here](https://github.com/ehmicky/design). Would it be possible to submit your PR to that repository instead? 
  - create a directory named `validate-path/`
  - add the logo under different formats as `validate-path/validate-path.png` (and `.svg`, or other formats you might have). No need to add variants (square vs rectangle, white background vs no background, sizes). But you can add different files for horizontal vs vertical vs logo-only as you did in the PR.
  - add the main logo to the `README` at the end of the `Logos` section.
  - add `validate-path/LICENSE.txt` with your CC-BY license.
  - add a sentence to the `README` after the trademark sentence to explain that the `validate-path` logo was designed by you and is licensed under CC-BY.

Thanks again for this contribution, this looks very good :) :tada: :tada: :tada:

**Comment by reallinfo** [comment]
Ofcourse, 

- FONT: [Montserrat](https://fonts.google.com/specimen/Montserrat)

I will do all the things you say. how does it look?

![vp](https://user-images.githubusercontent.com/36298335/56648715-7a034500-668c-11e9-9068-ca824ddd59b7.jpg)

**Comment by reallinfo** [comment]
Also, I have uploaded svg and ai files to [google drive](https://drive.google.com/open?id=1yG80TLCZi2ecz75AQFfr1vPT7Ve38PMf).

**Comment by ehmicky** [comment]
It looks good thanks! 

Could you please split the horizontal, vertical and logo-only variants into separate files? Like this, once it's hosted on the GitHub repository I was mentioned above, I can directly link to them. Thanks!

**Comment by reallinfo** [comment]
I sent a pr. https://github.com/ehmicky/design/pull/1 Please, Can you fix it if I made any mistakes? Also, you want to add a horizontal version to the readme file of this repo? Just suggestion. Btw, If you need logo for other projects, don't hesitate to contact me :)

**Comment by ehmicky** [comment]
I've added it to the `README`.

Thanks for this logo!
